# Generated by Django 5.2.17 on 2026-09-16 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'name', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'staff categories',
                'ordering': ('sort_order', 'name', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_date', models.DateField()),
                ('category_name_snapshot', models.CharField(max_length=120)),
                ('shift_name_snapshot', models.CharField(max_length=120)),
                ('shift_start_snapshot', models.TimeField()),
                ('shift_end_snapshot', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='checklists.checklistdefinition')),
            ],
            options={
                'ordering': ('-operational_date', 'category_name_snapshot', 'shift_start_snapshot'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name_snapshot', models.CharField(max_length=120)),
                ('section_order_snapshot', models.PositiveIntegerField()),
                ('task_label_snapshot', models.CharField(max_length=500)),
                ('task_order_snapshot', models.PositiveIntegerField()),
                ('allow_na_snapshot', models.BooleanField(default=False)),
                ('weekday_snapshot', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('scheduled_start_snapshot', models.TimeField(blank=True, null=True)),
                ('scheduled_end_snapshot', models.TimeField(blank=True, null=True)),
                ('current_state', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('na', 'N/A')], default='pending', max_length=16)),
                ('state_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='checklists.checklistinstance')),
            ],
            options={
                'ordering': ('section_order_snapshot', 'task_order_snapshot', 'scheduled_start_snapshot', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='checklists.checklistdefinition')),
            ],
            options={
                'ordering': ('sort_order', 'name', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ('sort_order', 'name', 'id'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('start_time', 'end_time'), name='unique_shift_window')],
            },
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_instances', to='checklists.shift'),
        ),
        migrations.AddField(
            model_name='checklistdefinition',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_definitions', to='checklists.shift'),
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='checklists.staffcategory')),
            ],
            options={
                'ordering': ('user__username', 'category__sort_order', 'category__name'),
            },
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_instances', to='checklists.staffcategory'),
        ),
        migrations.AddField(
            model_name='checklistdefinition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_definitions', to='checklists.staffcategory'),
        ),
        migrations.CreateModel(
            name='StaffContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('na', 'N/A')], max_length=16)),
                ('new_state', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('na', 'N/A')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='checklists.checklistitem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('allow_na', models.BooleanField(default=False, verbose_name='Allow N/A')),
                ('is_active', models.BooleanField(default=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('scheduled_start', models.TimeField(blank=True, null=True)),
                ('scheduled_end', models.TimeField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='checklists.checklistsection')),
            ],
            options={
                'ordering': ('section__sort_order', 'sort_order', 'weekday', 'id'),
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='source_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_items', to='checklists.taskdefinition'),
        ),
        migrations.AddConstraint(
            model_name='checklistsection',
            constraint=models.UniqueConstraint(fields=('definition', 'sort_order'), name='unique_section_order'),
        ),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_staff_category_assignment'),
        ),
        migrations.AddConstraint(
            model_name='checklistinstance',
            constraint=models.UniqueConstraint(fields=('operational_date', 'category', 'shift'), name='unique_operational_checklist'),
        ),
        migrations.AddConstraint(
            model_name='checklistdefinition',
            constraint=models.UniqueConstraint(fields=('category', 'shift'), name='unique_definition_category_shift'),
        ),
        migrations.AddConstraint(
            model_name='staffcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('previous_state__in', ['pending', 'completed', 'na'])), name='valid_contribution_previous_state'),
        ),
        migrations.AddConstraint(
            model_name='staffcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('new_state__in', ['pending', 'completed', 'na'])), name='valid_contribution_new_state'),
        ),
        migrations.AddConstraint(
            model_name='taskdefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scheduled_end__isnull', True), ('scheduled_start__isnull', True)), models.Q(('scheduled_end__isnull', False), ('scheduled_start__isnull', False)), _connector='OR'), name='task_schedule_times_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='taskdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('weekday__isnull', True)), fields=('section', 'sort_order'), name='unique_general_task_order'),
        ),
        migrations.AddConstraint(
            model_name='taskdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('weekday__isnull', False)), fields=('section', 'weekday', 'sort_order'), name='unique_weekday_task_order'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('instance', 'source_task'), name='unique_instance_source_task'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.CheckConstraint(condition=models.Q(('current_state__in', ['pending', 'completed', 'na'])), name='valid_checklist_item_state'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_state', 'na'), _negated=True), ('allow_na_snapshot', True), _connector='OR'), name='na_requires_snapshot_permission'),
        ),
    ]
