# Generated by Django 5.2.17 on 2026-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdefinition',
            name='seed_key',
            field=models.SlugField(blank=True, editable=False, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='seed_key',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='seed_key',
            field=models.SlugField(blank=True, editable=False, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='seed_key',
            field=models.SlugField(blank=True, editable=False, max_length=240, null=True, unique=True),
        ),
    ]
