# Generated by Django 5.2.17 on 2026-09-18 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_remove_legacy_membership_marker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSectionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'shift assignment section',
                'verbose_name_plural': 'shift assignment sections',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DiscrepancyExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'discrepancy explanation',
                'verbose_name_plural': 'discrepancy explanations',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SectionTaskMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'section task',
                'verbose_name_plural': 'section tasks',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='checklistdefinition',
            options={'ordering': ('sort_order', 'name', 'id'), 'verbose_name': 'shift assignment', 'verbose_name_plural': 'shift assignments'},
        ),
        migrations.AlterModelOptions(
            name='checklistinstance',
            options={'ordering': ('-operational_date', 'category_name_snapshot', 'shift_start_snapshot'), 'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ('section_order_snapshot', 'task_order_snapshot', 'scheduled_start_snapshot', 'id'), 'verbose_name': 'task instance', 'verbose_name_plural': 'task instances'},
        ),
        migrations.AlterModelOptions(
            name='checklistsection',
            options={'ordering': ('sort_order', 'name', 'id'), 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('name', 'id'), 'verbose_name': 'program', 'verbose_name_plural': 'programs'},
        ),
        migrations.AlterModelOptions(
            name='programmembership',
            options={'ordering': ('program__name', 'role', 'user__username'), 'verbose_name': 'program assignment', 'verbose_name_plural': 'program assignments'},
        ),
        migrations.AlterModelOptions(
            name='scheduledreportdelivery',
            options={'ordering': ('-period_end', 'program__name', 'cadence', 'recipient_email'), 'verbose_name': 'email report', 'verbose_name_plural': 'email reports'},
        ),
        migrations.AlterModelOptions(
            name='staffcategory',
            options={'ordering': ('sort_order', 'name', 'id'), 'verbose_name': 'position', 'verbose_name_plural': 'positions'},
        ),
        migrations.AlterModelOptions(
            name='staffcontribution',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'task entry', 'verbose_name_plural': 'task entries'},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ('first_name', 'last_name', 'id'), 'verbose_name': 'staff member', 'verbose_name_plural': 'staff'},
        ),
        migrations.AlterModelOptions(
            name='taskdefinition',
            options={'ordering': ('label', 'id'), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.RemoveConstraint(
            model_name='checklistsection',
            name='unique_section_order',
        ),
        migrations.RemoveConstraint(
            model_name='taskdefinition',
            name='unique_general_task_order',
        ),
        migrations.RemoveConstraint(
            model_name='taskdefinition',
            name='unique_weekday_task_order',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='weekday_snapshot',
        ),
        migrations.RemoveField(
            model_name='checklistsection',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='taskdefinition',
            name='section',
        ),
        migrations.RemoveField(
            model_name='taskdefinition',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='taskdefinition',
            name='weekday',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='requires_completion_note_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffcontribution',
            name='activity_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='requires_completion_note',
            field=models.BooleanField(default=False, verbose_name='Require completion note'),
        ),
        migrations.AddField(
            model_name='assignmentsectionmembership',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_memberships', to='checklists.checklistdefinition'),
        ),
        migrations.AddField(
            model_name='assignmentsectionmembership',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_memberships', to='checklists.checklistsection'),
        ),
        migrations.AddField(
            model_name='checklistdefinition',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='assignments', through='checklists.AssignmentSectionMembership', to='checklists.checklistsection'),
        ),
        migrations.AddField(
            model_name='discrepancyexplanation',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_explanations', to='checklists.checklistinstance'),
        ),
        migrations.AddField(
            model_name='discrepancyexplanation',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_discrepancy_explanations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discrepancyexplanation',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_explanations', to='checklists.staffmember'),
        ),
        migrations.AddField(
            model_name='sectiontaskmembership',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_memberships', to='checklists.checklistsection'),
        ),
        migrations.AddField(
            model_name='sectiontaskmembership',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_memberships', to='checklists.taskdefinition'),
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='sections', through='checklists.SectionTaskMembership', to='checklists.taskdefinition'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsectionmembership',
            constraint=models.UniqueConstraint(fields=('assignment', 'section'), name='unique_assignment_section_membership'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsectionmembership',
            constraint=models.UniqueConstraint(fields=('assignment', 'sort_order'), name='unique_assignment_section_order'),
        ),
        migrations.AddConstraint(
            model_name='discrepancyexplanation',
            constraint=models.UniqueConstraint(fields=('instance', 'staff'), name='unique_instance_staff_discrepancy'),
        ),
        migrations.AddConstraint(
            model_name='sectiontaskmembership',
            constraint=models.UniqueConstraint(fields=('section', 'task'), name='unique_section_task_membership'),
        ),
        migrations.AddConstraint(
            model_name='sectiontaskmembership',
            constraint=models.UniqueConstraint(fields=('section', 'sort_order'), name='unique_section_task_order'),
        ),
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX auth_user_username_ci_unique ON auth_user (LOWER(username))',
            reverse_sql='DROP INDEX auth_user_username_ci_unique',
        ),
    ]
